
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package compilador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TOK_MAYORIGUAL = 22;
  public static final int TOK_COMA = 29;
  public static final int TOK_LLAVEIZQUIERDA = 9;
  public static final int TOK_FALSE = 33;
  public static final int TOK_ASTERISCO = 4;
  public static final int TOK_ELSE = 13;
  public static final int TOK_ASIGNACION = 30;
  public static final int TOK_SCANF = 17;
  public static final int TOK_PARENTESISIZQUIERDO = 7;
  public static final int TOK_CONSTANTE_ENTERA = 32;
  public static final int TOK_MAS = 2;
  public static final int EOF = 0;
  public static final int TOK_IGUAL = 25;
  public static final int error = 1;
  public static final int TOK_IDENTIFICADOR = 35;
  public static final int TOK_PUNTOYCOMA = 31;
  public static final int TOK_INT = 16;
  public static final int TOK_LLAVEDERECHA = 10;
  public static final int TOK_DIVISION = 5;
  public static final int TOK_NOT = 26;
  public static final int TOK_AND = 28;
  public static final int TOK_MENOS = 3;
  public static final int TOK_MENOR = 21;
  public static final int TOK_PARENTESISDERECHO = 8;
  public static final int TOK_ERROR = 11;
  public static final int TOK_MAYOR = 20;
  public static final int TOK_DISTINTO = 24;
  public static final int TOK_PRINTF = 18;
  public static final int TOK_MENORIGUAL = 23;
  public static final int TOK_OR = 27;
  public static final int TOK_MAIN = 19;
  public static final int TOK_WHILE = 12;
  public static final int TOK_BOOLEAN = 15;
  public static final int TOK_IF = 14;
  public static final int TOK_MENOSU = 6;
  public static final int TOK_TRUE = 34;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "TOK_MAS",
  "TOK_MENOS",
  "TOK_ASTERISCO",
  "TOK_DIVISION",
  "TOK_MENOSU",
  "TOK_PARENTESISIZQUIERDO",
  "TOK_PARENTESISDERECHO",
  "TOK_LLAVEIZQUIERDA",
  "TOK_LLAVEDERECHA",
  "TOK_ERROR",
  "TOK_WHILE",
  "TOK_ELSE",
  "TOK_IF",
  "TOK_BOOLEAN",
  "TOK_INT",
  "TOK_SCANF",
  "TOK_PRINTF",
  "TOK_MAIN",
  "TOK_MAYOR",
  "TOK_MENOR",
  "TOK_MAYORIGUAL",
  "TOK_MENORIGUAL",
  "TOK_DISTINTO",
  "TOK_IGUAL",
  "TOK_NOT",
  "TOK_OR",
  "TOK_AND",
  "TOK_COMA",
  "TOK_ASIGNACION",
  "TOK_PUNTOYCOMA",
  "TOK_CONSTANTE_ENTERA",
  "TOK_FALSE",
  "TOK_TRUE",
  "TOK_IDENTIFICADOR"
  };
}

